require:
  - rubocop-rails
  - rubocop-rspec
  - ./lib/rubocop/cop/style/content_helper

Rails:
  Enabled: true

Rails/HelperInstanceVariable:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Rails/UnknownEnv:
  Environments:
    - development
    - production
    - staging
    - test

# this cop's autocorrect can corrupt files so consider disabling it before running an autocorrect
Rails/DynamicFindBy:
  Enabled: true

# this cop's autocorrect can break chronic so consider disabling it before running an autocorrect
Rails/TimeZone:
  Enabled: true

# this cop's autocorrect can corrupt files so consider disabling it before running an autocorrect
Rails/Validation:
  Enabled: true

Rails/FilePath:
  EnforcedStyle: arguments

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/FirstHashElementIndentation:
  Enabled: false

Layout/MultilineMethodCallBraceLayout:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Layout/LineLength:
  Enabled: true
  Max: 100
  Exclude:
    - Gemfile

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

# this cop's autocorrect can corrupt files so consider disabling it before running an autocorrect
Security/YAMLLoad:
  Enabled: true

Style/AsciiComments:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/ContentHelper:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GlobalVars:
  AllowedVariables: [$redis, $lock_manager, $rollout, $sidekiq_shutdown_pending]

Style/GuardClause:
  Enabled: false

Style/HashSyntax:
  Enabled: true

Style/IfUnlessModifier:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

# this cop's autocorrect can corrupt files so consider disabling it before running an autocorrect
Style/OrAssignment:
  Enabled: true

# this cop's autocorrect can corrupt files so consider disabling it before running an autocorrect
Style/RedundantCondition:
  Enabled: true

# this cop's autocorrect can corrupt files so consider disabling it before running an autocorrect
Style/RedundantInterpolation:
  Enabled: true

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes


# Rspec cops
RSpec/ContextWording:
  Enabled: false
RSpec/EmptyLineAfterExampleGroup:
  Enabled: false
RSpec/EmptyLineAfterHook:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/ExampleWording:
  Enabled: false
RSpec/Focus:
  Enabled: true
RSpec/HookArgument:
  Enabled: false
RSpec/InstanceVariable:
  Enabled: false
RSpec/LeakyConstantDeclaration:
  Enabled: false
RSpec/MessageSpies:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/NamedSubject:
  Enabled: false
RSpec/NestedGroups:
  Enabled: false
RSpec/NotToNot:
  Enabled: false
RSpec/PredicateMatcher:
  Enabled: false
RSpec/SubjectStub:
  Enabled: false
RSpec/DescribeClass:
  Enabled: false
